# Server
server.port=8080

# MySQL Database Config
spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:49428/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=BtSAXXAuWPwWkGFMggWDSLDONjxEItRn

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# CORS
app.cors.allowedOrigin=http://localhost:5173

# JWT
jwt.secret=THIS_IS_A_SUPER_SECRET_KEY_123456789_THIS_IS_LONG
jwt.expiration=86400000
